spring:
  application:
    name: xs-clean-demo
  http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.youxinpai.cloud.domain
  configuration:
    default-enum-type-handler: com.yxp.common.db.plugin.mybatis.typehandler.CodeEnumTypeHandler

debug: true
